# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.oh-my-zsh/custom
export TERM="xterm-256color"
setopt RM_STAR_WAIT
setopt interactivecomments
setopt CORRECT

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_COLOR_SCHEME='dark'

plugins=(zsh-autosuggestions common-aliases git)

source $ZSH/oh-my-zsh.sh

DEFAULT_USER=`whoami`
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

# Load more colorful dircolors
eval `dircolors ~/.dircolors`


# eoltas b2b {{
alias cdeoltasb2b='cd /var/www/eoltas-projects/b2b'

alias mountEoltasb2b='sudo mount docker.dev:/home/project/projects/eoltas/b2b/src /var/www/eoltas-projects/b2b'
alias umountEoltasb2b='sudo umount docker.dev:/home/project/projects/eoltas/b2b/src'
alias sshEoltasb2b='ssh project@dev.b2b.eoltas.dev'

# }}

# eoltas axapta {{
alias cdeoltasaxapta='cd /var/www/eoltas-projects/axapta'

alias mountEoltasaxapta='sudo mount docker.dev:/home/project/projects/eoltas/axapta/src /var/www/eoltas-projects/axapta'
alias umountEoltasaxapta='sudo umount docker.dev:/home/project/projects/eoltas/axapta/src'
alias sshEoltasaxapta='ssh project@dev.axapta.eoltas.dev'

# }}

# eoltas pim {{
alias cdeoltaspim='cd /var/www/eoltas-projects/pim'

alias mountEoltaspim='sudo mount docker.dev:/home/project/projects/eoltas/pim/src /var/www/eoltas-projects/pim'
alias umountEoltaspim='sudo umount docker.dev:/home/project/projects/eoltas/pim/src'
alias sshEoltaspim='ssh project@dev.pim.eoltas.dev'
# }}

# eoltas central storage {{
alias mountEoltasCentralStorage='sudo mount docker.dev:/home/project/projects/eoltas/central-storage/src /var/www/eoltas-projects/central-storage'
alias umountEoltasCentralStorage='sudo umount docker.dev:/home/project/projects/eoltas/central-storage/src'
alias sshEoltasCentralStorage='ssh project@dev.central-storage.eoltas.dev'
# }}

