export ZSH=$HOME/.oh-my-zsh
export VISUAL=vim
export EDITOR="$VISUAL"
eval `dircolors ~/.dir_colors`

source ~/.fonts/fontawesome-regular.sh

ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_COLOR_SCHEME='dark'

POWERLEVEL9K_MODE='awesome-fontconfig'
#POWERLEVEL9K_MODE="nerdfont-complete"

DEFAULT_USER="rokas"

plugins=(zsh-autosuggestions git common-aliases tmux)

ZSH_TMUX_AUTOSTART=true

source $ZSH/oh-my-zsh.sh

docker-ip() {
  docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$@"
}

color-ssh() {
    trap "bash .colorterm.sh" INT EXIT
    if [[ "$*" =~ "Live" ]]; then
        bash .colorterm.sh prod
    elif [[ "$*" =~ "Stage" ]]; then
        bash .colorterm.sh dev
    else
        bash .colorterm.sh none
    fi
    ssh $*
}

#compdef _ssh color-ssh=ssh
#alias ssh=color-ssh

alias sfcc='bin/console cache:clear --no-warmup && bin/console cache:warmup'
alias asfcc='app/console cache:clear --no-warmup && app/console cache:warmup'
alias rrmouse='sudo  modprobe -r psmouse && sudo modprobe psmouse'
alias cdeoltas='cd /var/www/eoltas'

alias workspace='docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -u laradock -it workspace /bin/zsh'

alias cat='pygmentize -g'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.symfony/bin:$PATH"
